## project: Generate .xcodeproj file using XcodeGen utility
project:
	mint run "yonaskolb/XcodeGen"

## swiftgen: Trigger code generation from assets with swiftgen tool
swiftgen:
	mint run swiftgen

.PHONY:
generate:
	mint run swiftgen/swiftgen
